version: "3.6"

services:
  railmail:
    build: .
    environment:
      SMTP_HOST
      SMTP_PORT
      SMTP_USERNAME
      SMTP_PASSWORD
      AMQP_HOST
      AMQP_PORT
      AMQP_USERNAME
      AMQP_PASSWORD
      AMQP_QUEUE
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq