version: "3.6"

services:
  
  railmail:
    build: .
    restart: on-failure
    environment:
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USERNAME: p33ijercxqsti6cb@ethereal.email
      SMTP_PASSWORD: Hn9CefuuktzY5wZDSs
      SMTP_SENDER: test@ethereal.email
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      AMQP_QUEUE: railmail-ingest
    ports:
      - "5000:80"
  
  rabbitmq:
    image: rabbitmq