version: "3.6"

services:
  railmail:
    build: .
    environment:
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USERNAME: p33ijercxqsti6cb@ethereal.email
      SMTP_PASSWORD: Hn9CefuuktzY5wZDSs
      SMTP_SENDER: test@ethereal.email
      # AMQP_HOST
      # AMQP_PORT
      # AMQP_USERNAME
      # AMQP_PASSWORD
      # AMQP_QUEUE
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq